export const STRINGS_EN = {
  appTitle: "Bingkai", docTitle: "Bingkai",
  modes: { frame: "Frame", crop: "Crop", collage: "Collage", carousel: "Carousel" },
  emptyTitle: "No slides yet.",
  emptySub: "Add your first slide to start your post.",
  import: "Import Photos",
  addFirstSlide: "Add First Slide", slideWord: "Slide",
  dropHint: "or drag & drop here",
  addPhoto: "Add photo",
  loading: "Loading\u2026",
  errDecode: "Could not read image: ",
  errNoImages: "No valid image files.",
  removeConfirm: "Remove this photo from the session?",
  modeSoon: "This mode arrives in the next phase.",
  ratio: "Ratio", original: "Original",
  margin: "Margin", background: "Background", bgSolid: "Color", bgBlur: "Blur",
  frameColor: "Frame color",
  frameEnable: "Frame", frameOn: "On", frameOff: "Off",
  exportSize: "Export size", sizeIG: "Instagram 1080", sizeHi: "High resolution",
  quality: "JPEG quality", format: "Format", fmtJpeg: "JPEG (photo)", fmtPng: "PNG (design)",
  exportBtn: "Export", exporting: "Exporting\u2026",
  igNote: "1080px sRGB \u2014 Instagram's native width. No re-scaling on IG's side.",
  hiNote: "Short side up to 2160px. IG downsizes to 1080 on upload.",
  pngNote: "PNG suits text/flat graphics, not photos. Files are far larger; IG converts to JPEG anyway.",
  upscaleWarn: "Source is smaller than 1080px \u2014 the result is upscaled and looks soft.",
  shared: "Shared via the share sheet.",
  downloaded: "Saved to your Downloads folder (not directly to the Gallery).",
  exportFail: "Export failed. Try reducing size or quality.",
  free: "Free", reset: "Reset",
  cropHint: "Drag to pan \u00b7 pinch to zoom",
  cropExportNote: "Using export profile: Instagram 1080 \u00b7 JPEG q92. Change it in the Export dialog.",
  grid: "Grid", gutter: "Gutter", outerMargin: "Outer margin", gutterColor: "Gutter color",
  collageHint: "Tap to select \u00b7 drag to pan \u00b7 drag onto another cell to swap",
  needTwoForCollage: "Add more photos to fill the cells.",
  tiles: "Tile count", tileRatio: "Tile ratio", fill: "Fill",
  fillCover: "Fill (cover)", fillFit: "Fit",
  carouselHint: "Swipe \u2194 preview tiles \u00b7 drag \u2195 reposition \u00b7 pinch to zoom",
  carouselHintMove: "Drag to reposition \u00b7 pinch to zoom",
  carouselHintBrowse: "Swipe \u2194 to preview tiles",
  previewTitle: "Export preview",
  previewCarousel: "Carousel preview",
  previewBatch: "Preview all",
  carouselNote: "Exports N 1080px images in posting order. Each tile edge is exactly 1080px so IG won't shift the seams.",
  sharedN: "Shared via the share sheet.",
  zipped: "ZIP saved to Downloads.",
  downloadedN: "tiles downloaded separately (share sheet unavailable).",
  presets: "Presets", savePreset: "+ Save", promptName: "Preset name:",
  presetSaved: "Preset saved.", deletePreset: "Delete this preset?",
  blurStrength: "Blur strength", install: "Install app",
  // settings / history / newer controls
  settingsTitle: "Settings", namePrefixLabel: "Export name prefix", numberingLabel: "Numbering",
  numberDate: "Date/time", numberSeq: "Sequence", language: "Language", example: "Example: ",
  historyTitle: "Export history", historyEmpty: "No exports yet.", clearAll: "Clear all",
  save: "Save", preview: "Preview", all: "All", rotate90: "Rotate 90\u00b0", layout: "Layout",
  interaction: "Interaction", adjMove: "Reposition", adjBrowse: "Preview tiles",
  portrait: "Portrait", landscape: "Landscape",
  postTitle: "Reorder slides", postEmpty: "No photos yet \u2014 import some to start your post.",
  postSlides: "slides", postSlide1: "slide", postImages: "images", postImage1: "image",
  postReorderHint: "Drag the handle to reorder.",
  exportPost: "Export post",
  chooseLayout: "Choose a layout", layoutTitle: "Choose a layout",
  lpGrid: "Grid", lpLayouts: "Layouts", cellFill: "Fill selected cell",
};

export const STRINGS_ID = {
  appTitle: "Bingkai", docTitle: "Bingkai",
  modes: { frame: "Bingkai", crop: "Potong", collage: "Kolase", carousel: "Carousel" },
  emptyTitle: "Belum ada slide.",
  emptySub: "Tambah slide pertama untuk memulai post.",
  import: "Impor Foto",
  addFirstSlide: "Tambah Slide Pertama", slideWord: "Slide",
  dropHint: "atau seret & lepas ke sini",
  addPhoto: "Tambah foto",
  loading: "Memuat\u2026",
  errDecode: "Gagal membaca gambar: ",
  errNoImages: "Tidak ada berkas gambar yang valid.",
  removeConfirm: "Hapus foto ini dari sesi?",
  modeSoon: "Mode ini aktif pada fase berikutnya.",
  ratio: "Rasio", original: "Asli",
  margin: "Margin", background: "Latar belakang", bgSolid: "Warna", bgBlur: "Blur",
  frameColor: "Warna bingkai",
  frameEnable: "Bingkai", frameOn: "Aktif", frameOff: "Nonaktif",
  exportSize: "Ukuran ekspor", sizeIG: "Instagram 1080", sizeHi: "Resolusi tinggi",
  quality: "Kualitas JPEG", format: "Format", fmtJpeg: "JPEG (foto)", fmtPng: "PNG (desain)",
  exportBtn: "Ekspor", exporting: "Mengekspor\u2026",
  igNote: "1080px sRGB \u2014 lebar native Instagram. Tidak ada penskalaan ulang di sisi IG.",
  hiNote: "Sisi pendek hingga 2160px. IG akan menurunkan ke 1080 saat diunggah.",
  pngNote: "PNG cocok untuk teks/grafik datar, bukan foto. Berkas jauh lebih besar; IG tetap mengubahnya jadi JPEG.",
  upscaleWarn: "Sumber lebih kecil dari 1080px \u2014 hasil akan di-upscale dan terlihat lembut.",
  shared: "Dibagikan lewat lembar berbagi.",
  downloaded: "Tersimpan ke folder Unduhan (bukan langsung ke Galeri).",
  exportFail: "Ekspor gagal. Coba kurangi ukuran atau kualitas.",
  free: "Bebas", reset: "Atur ulang",
  cropHint: "Seret untuk geser \u00b7 cubit untuk zoom",
  cropExportNote: "Memakai profil ekspor: Instagram 1080 \u00b7 JPEG q92. Ubah di dialog Ekspor.",
  grid: "Kisi", gutter: "Jarak", outerMargin: "Margin luar", gutterColor: "Warna jarak",
  collageHint: "Ketuk untuk pilih \u00b7 seret untuk geser \u00b7 seret ke sel lain untuk tukar",
  needTwoForCollage: "Tambah lebih banyak foto untuk mengisi sel.",
  tiles: "Jumlah tile", tileRatio: "Rasio tile", fill: "Pengisian",
  fillCover: "Penuh (cover)", fillFit: "Muat (fit)",
  carouselHint: "Geser \u2194 pratinjau tile \u00b7 geser \u2195 atur posisi \u00b7 cubit untuk zoom",
  carouselHintMove: "Seret untuk atur posisi \u00b7 cubit untuk zoom",
  carouselHintBrowse: "Geser \u2194 untuk pratinjau tile",
  previewTitle: "Pratinjau ekspor",
  previewCarousel: "Pratinjau carousel",
  previewBatch: "Pratinjau semua",
  carouselNote: "Mengekspor N gambar 1080px dalam urutan unggah. Tepi tiap tile sama persis 1080px agar IG tidak menggeser jahitan.",
  sharedN: "Dibagikan lewat lembar berbagi.",
  zipped: "ZIP tersimpan ke Unduhan.",
  downloadedN: "tiap tile diunduh terpisah (lembar berbagi tidak tersedia).",
  presets: "Preset", savePreset: "+ Simpan", promptName: "Nama preset:",
  presetSaved: "Preset disimpan.", deletePreset: "Hapus preset ini?",
  blurStrength: "Kekuatan blur", install: "Pasang aplikasi",
  settingsTitle: "Pengaturan", namePrefixLabel: "Awalan nama ekspor", numberingLabel: "Penomoran",
  numberDate: "Tanggal/waktu", numberSeq: "Urutan", language: "Bahasa", example: "Contoh: ",
  historyTitle: "Riwayat ekspor", historyEmpty: "Belum ada ekspor.", clearAll: "Hapus semua",
  save: "Simpan", preview: "Pratinjau", all: "Semua", rotate90: "Putar 90\u00b0", layout: "Tata letak",
  interaction: "Interaksi", adjMove: "Atur posisi", adjBrowse: "Pratinjau tile",
  portrait: "Potret", landscape: "Lanskap",
  postTitle: "Susun ulang slide", postEmpty: "Belum ada foto \u2014 impor dulu untuk memulai post.",
  postSlides: "slide", postSlide1: "slide", postImages: "gambar", postImage1: "gambar",
  postReorderHint: "Seret gagang untuk mengurutkan.",
  exportPost: "Ekspor post",
  chooseLayout: "Pilih tata letak", layoutTitle: "Pilih tata letak",
  lpGrid: "Kisi", lpLayouts: "Tata letak", cellFill: "Isi sel terpilih",
};

export let LANG = "en";
export let STRINGS = STRINGS_EN;

// Sole owner of language-state mutation. ui.applyLang() calls this instead of
// reassigning STRINGS/LANG directly — imported bindings are read-only in the
// consumer module, so the cross-scope reassignment that worked in the flat
// single-scope file would throw under ES modules. Live bindings propagate the
// new object to every importer automatically. (RCA: MODULE_SPLIT_SPEC §4.)
export function setLang(lang) {
  LANG = (lang === "id") ? "id" : "en";
  STRINGS = (LANG === "id") ? STRINGS_ID : STRINGS_EN;
}
